accessibility: protected
containerPort: 80
autoscale: enabled
resources:
    requests:
        cpu: 50m
        memory: 64Mi
    limits:
        cpu: 50m
        memory: 64Mi

istio:
    enabled: true
    tlsMode: STRICT
    gateway:
        minReplicas: 2
        maxReplicas: 4
        resources:
            requests:
                cpu: 50m
                memory: 64Mi
            limits:
                cpu: 50m
                memory: 64Mi
